{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.panyukovnn",
    "module": "logging-starter-3",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-3-1.3-SNAPSHOT.jar",
          "url": "logging-starter-3-1.3-SNAPSHOT.jar",
          "size": 9714,
          "sha512": "7d20b82d78f03b31ac51bc2f14527499d04eb20f5d72a57dca45aee9aafe6c4f09b53575d6d91998c4b3f2b6dff99761bdebad1f3f8960f5177cf597dc97d28b",
          "sha256": "b5f1641f326e2bec03a01b0dc8d9ad07d4d9bf3e251770caa0ec9460edb9c0ac",
          "sha1": "afe86f513eb2ef39a7fcd2bc1d25ca577b1f7a70",
          "md5": "d0dea04ba9b486863551c648a4958536"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-3-1.3-SNAPSHOT.jar",
          "url": "logging-starter-3-1.3-SNAPSHOT.jar",
          "size": 9714,
          "sha512": "7d20b82d78f03b31ac51bc2f14527499d04eb20f5d72a57dca45aee9aafe6c4f09b53575d6d91998c4b3f2b6dff99761bdebad1f3f8960f5177cf597dc97d28b",
          "sha256": "b5f1641f326e2bec03a01b0dc8d9ad07d4d9bf3e251770caa0ec9460edb9c0ac",
          "sha1": "afe86f513eb2ef39a7fcd2bc1d25ca577b1f7a70",
          "md5": "d0dea04ba9b486863551c648a4958536"
        }
      ]
    }
  ]
}
