{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.panyukovnn",
    "module": "logging-starter-3",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-3-1.2-SNAPSHOT.jar",
          "url": "logging-starter-3-1.2-SNAPSHOT.jar",
          "size": 9683,
          "sha512": "77f42aba676f79a76dab18bf47316f467061ac6d50f9c37764edc87ff564542a048da7f5c7acc15866da83893b9d5eb8444ed2565886e50d1f6c56b11d2f56ad",
          "sha256": "ae23d01ab8dc40ff17119b75b8998b1a2e3d75bb289336093a720db8cd143385",
          "sha1": "04f1ceb5ccf36380f893b16f82edc83a59bcf8fb",
          "md5": "e55275c7127392d2065583b0bcbdbb6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-3-1.2-SNAPSHOT.jar",
          "url": "logging-starter-3-1.2-SNAPSHOT.jar",
          "size": 9683,
          "sha512": "77f42aba676f79a76dab18bf47316f467061ac6d50f9c37764edc87ff564542a048da7f5c7acc15866da83893b9d5eb8444ed2565886e50d1f6c56b11d2f56ad",
          "sha256": "ae23d01ab8dc40ff17119b75b8998b1a2e3d75bb289336093a720db8cd143385",
          "sha1": "04f1ceb5ccf36380f893b16f82edc83a59bcf8fb",
          "md5": "e55275c7127392d2065583b0bcbdbb6a"
        }
      ]
    }
  ]
}
